services:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=cornel
      - MYSQL_PASSWORD=sefusefu
      - MYSQL_ROOT_PASSWORD=sefusefu
      - MYSQL_DATABASE=mydatabase

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=cornel
      - POSTGRES_PASSWORD=sefusefu
      - POSTGRES_DB=mydatabase