version: '3.6'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=cornel
      - MYSQL_PASSWORD=sefusefu
      - MYSQL_ROOT_PASSWORD=sefusefu
      - MYSQL_DATABASE=mydatabase

